"""
Voice of Customer Agent (Agent 1) — the output attribution check.

The decision this implements: names are NOT stripped or replaced before the
model sees the evidence. Replacing them would stop the agent seeing that
three documents concern the same customer, which is how a single-source
finding is identified, and a single-source finding is Low confidence
however emphatically it was stated.

So the attribution policy is enforced in two layers:

  1. The prompt instruction, as before.
  2. This module: after each report is generated, a deterministic scan for
     every customer name the platform knows about -- named customers from
     voc_customers, plus every value in a CSV column mapped to the
     `customer` role -- replacing each occurrence with a segment label.
     Needed regardless of the prompt, because web search is on: the model
     can learn a customer's name from public sources without ever having
     been told it.

It is a check, not a guarantee, and the output says so: it cannot catch a
name it was never given, a programme or platform unique to one customer, or
a quotation someone would recognise. Those remain prompt-only.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Iterable

from voice_of_customer.context import Customer, Segment

# Below this length a name is matched case-sensitively: "GE" must not
# rewrite every "ge" inside an unrelated word or sentence.
_CASE_INSENSITIVE_MIN_LEN = 4
_MIN_NAME_LEN = 2


@dataclass(frozen=True)
class NameEntry:
    name: str
    replacement: str


def _label(segment_key: str, segments: dict[str, Segment]) -> str:
    seg = segments.get(segment_key)
    if seg is not None:
        return f"[customer in segment: {seg.segment_name}]"
    return "[customer — name withheld]"


def build_name_list(
    customers: Iterable[Customer],
    segments: Iterable[Segment],
    extra_names: Iterable[str] = (),
) -> list[NameEntry]:
    """Longest names first, so "Acme Aerospace Ltd" is replaced whole before
    "Acme" could match inside it."""
    by_key = {s.segment_key: s for s in segments}
    entries: dict[str, NameEntry] = {}
    for c in customers:
        name = (c.customer_name or "").strip()
        if len(name) >= _MIN_NAME_LEN:
            entries[name.lower()] = NameEntry(name, _label(c.segment_key, by_key))
    for raw in extra_names:
        name = (raw or "").strip()
        if len(name) >= _MIN_NAME_LEN and name.lower() not in entries:
            entries[name.lower()] = NameEntry(name, _label("", by_key))
    return sorted(entries.values(), key=lambda e: len(e.name), reverse=True)


def _pattern(name: str) -> re.Pattern:
    flags = re.IGNORECASE if len(name) >= _CASE_INSENSITIVE_MIN_LEN else 0
    return re.compile(rf"(?<!\w){re.escape(name)}(?!\w)", flags)


def apply_attribution_check(text: str, entries: list[NameEntry], policy: str) -> tuple[str, int]:
    """(checked text, replacements made). A no-op under `named`, where the
    customer has confirmed names may appear."""
    if policy == "named" or not entries:
        return text, 0
    total = 0
    for entry in entries:
        text, n = _pattern(entry.name).subn(entry.replacement, text)
        total += n
    return text, total


def attribution_check_note(policy: str, names_checked: int, replacements: int) -> str:
    """Appended to Report 1 deterministically -- not generated by the model,
    so it is always present and always accurate about what was done."""
    if policy == "named":
        return (
            "## Attribution check\n\n"
            "Attribution policy: **named**. Customers may be named directly, as the customer has "
            "confirmed is permitted, so no output check was applied."
        )
    if names_checked == 0:
        return (
            "## Attribution check\n\n"
            f"Attribution policy: **{policy}**. No customer names were supplied — none in the named "
            "customers list and no CSV column mapped as customer — so there was nothing to check "
            "the output against. Attribution in this run rests on the prompt instruction alone."
        )
    return (
        "## Attribution check\n\n"
        f"Attribution policy: **{policy}**. After generation, every report in this run was checked "
        f"against the {names_checked} customer name(s) known to the platform; "
        f"{replacements} occurrence(s) were replaced with a segment label.\n\n"
        "This is a check, not a guarantee. It cannot catch a customer name it was not given, a "
        "programme or platform unique to one customer, or a quoted phrase someone would recognise."
    )
