"""
Intermediate structure -> .docx bytes.

Builds against the reference template (template.docx, generated by
build_template.py) rather than defining styles programmatically -- see
word_export_briefing.md, "python-docx gotchas".

Memory shape matters here: the production instance has 414MB RAM
(word_export_briefing.md, "Memory constraint"). `ExportBuilder.add_report`
takes raw markdown and parses + renders it internally so the caller never
holds more than one report's parsed structure alongside the growing
document -- the parsed structure for report N is garbage-collectable before
report N+1 is even read from the database cursor.
"""
from __future__ import annotations

import logging
import pathlib

from docx import Document
from docx.enum.section import WD_ORIENT, WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK, WD_COLOR_INDEX
from docx.opc.constants import RELATIONSHIP_TYPE
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from app.export import exhibits
from app.export.markdown_parser import (
    BulletListBlock,
    ExhibitBlock,
    Heading,
    HorizontalRule,
    KeyInsightsBox,
    Paragraph,
    Run,
    SCQABlock,
    TableBlock,
    parse_report,
)

logger = logging.getLogger(__name__)

TEMPLATE_PATH = pathlib.Path(__file__).parent / "template.docx"

_USABLE_WIDTH_PORTRAIT_IN = 6.5  # 8.5in page - 1in margins each side
_USABLE_WIDTH_LANDSCAPE_IN = 9.0  # 11in page - 1in margins each side

_RING_SHADES = ["D9E4F0", "C7D8EA", "B4CCE3"]  # TAM -> SAM -> SOM, progressively deeper
_HEADER_SHADE = "DCE6F1"
_KEY_INSIGHT_SHADE = "F0F4F8"
_SCQA_SHADE = "EEF2F7"
_SCQA_ANSWER_SHADE = "DCE6F1"
_FALLBACK_SHADE = "F5F5F5"
_FALLBACK_BORDER = "BFBFBF"

_SYMBOL_FONT = "Segoe UI Symbol"  # explicit, run-level -- box-drawing/Harvey Ball glyph coverage
_ACCENT = RGBColor(0x1F, 0x3A, 0x5F)


# ---------------------------------------------------------------------------
# Low-level OOXML helpers (python-docx has no API for these)
# ---------------------------------------------------------------------------


def _set_run_font(run, name: str) -> None:
    """Set a font on a run at the XML level (ascii/hAnsi/eastAsia/cs), not
    just `run.font.name` -- Word can otherwise substitute a different font
    for glyphs it buckets as "east asian" or "complex script", which is
    exactly the failure mode word_export_briefing.md calls out for the
    Harvey Ball and box-drawing glyphs. Must be set on the run, not inherited
    from a paragraph or table style.
    """
    run.font.name = name
    rPr = run._r.get_or_add_rPr()
    rFonts = rPr.find(qn("w:rFonts"))
    if rFonts is None:
        rFonts = OxmlElement("w:rFonts")
        rPr.append(rFonts)
    for attr in ("w:ascii", "w:hAnsi", "w:eastAsia", "w:cs"):
        rFonts.set(qn(attr), name)


def _shade_cell(cell, hex_color: str) -> None:
    """Cell background shading. `w:shd` needs `w:val="clear"` or it renders
    solid black instead of the intended fill (word_export_briefing.md)."""
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def _set_cell_borders(cell, hex_color: str) -> None:
    tcPr = cell._tc.get_or_add_tcPr()
    borders = OxmlElement("w:tcBorders")
    for edge in ("top", "left", "bottom", "right"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"), "single")
        el.set(qn("w:sz"), "4")
        el.set(qn("w:color"), hex_color)
        borders.append(el)
    tcPr.append(borders)


def _force_fixed_layout(table) -> None:
    """Explicit absolute widths only survive if the table layout is fixed --
    otherwise Word's autofit algorithm overrides them, which is why nested
    TAM/SAM/SOM tables collapse without this (word_export_briefing.md)."""
    table.autofit = False
    tblPr = table._tbl.tblPr
    layout = OxmlElement("w:tblLayout")
    layout.set(qn("w:type"), "fixed")
    tblPr.append(layout)


def _set_table_width(table, width_in: float, col_widths_in: list[float] | None = None) -> None:
    _force_fixed_layout(table)
    widths = col_widths_in or [width_in / max(1, len(table.columns))] * len(table.columns)
    for col, w in zip(table.columns, widths):
        col.width = Inches(w)
    for row in table.rows:
        for cell, w in zip(row.cells, widths):
            cell.width = Inches(w)


def _add_hyperlink(paragraph, url: str, text: str, *, bold: bool = False, italic: bool = False) -> None:
    """Insert a real Word hyperlink. python-docx has no API for this --
    standard raw-XML recipe: a relationship + a `w:hyperlink` element
    wrapping a run."""
    part = paragraph.part
    r_id = part.relate_to(url, RELATIONSHIP_TYPE.HYPERLINK, is_external=True)
    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), r_id)

    new_run = OxmlElement("w:r")
    rPr = OxmlElement("w:rPr")
    color = OxmlElement("w:color")
    color.set(qn("w:val"), "1F3A5F")
    rPr.append(color)
    u = OxmlElement("w:u")
    u.set(qn("w:val"), "single")
    rPr.append(u)
    if bold:
        rPr.append(OxmlElement("w:b"))
    if italic:
        rPr.append(OxmlElement("w:i"))
    new_run.append(rPr)
    t = OxmlElement("w:t")
    t.set(qn("xml:space"), "preserve")
    t.text = text
    new_run.append(t)
    hyperlink.append(new_run)
    paragraph._p.append(hyperlink)


def _insert_toc_field(paragraph) -> None:
    """TOC is a field code -- no python-docx helper exists. Word populates
    it only when the user accepts the "update fields" prompt (or presses
    F9); that's expected and noted in the PR per word_export_briefing.md."""
    run = paragraph.add_run()
    r = run._r

    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    begin.set(qn("w:dirty"), "true")

    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = 'TOC \\o "1-2" \\h \\z \\u'

    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")

    placeholder = OxmlElement("w:t")
    placeholder.text = 'Right-click and choose "Update Field" to build the table of contents.'

    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")

    for el in (begin, instr, separate, placeholder, end):
        r.append(el)


def _hr_paragraph(doc) -> None:
    """`---` -> a paragraph bottom border. Never a table (an explicit
    word_export_briefing.md gotcha)."""
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "6")
    bottom.set(qn("w:space"), "4")
    bottom.set(qn("w:color"), "C8C8C8")
    pBdr.append(bottom)
    pPr.append(pBdr)


def _set_repeat_header_row(table) -> None:
    """Repeat the table's first row as a header on every page it spans.
    No python-docx API for `w:tblHeader` -- raw XML on the row's `w:trPr`."""
    if not table.rows:
        return
    trPr = table.rows[0]._tr.get_or_add_trPr()
    header = OxmlElement("w:tblHeader")
    header.set(qn("w:val"), "true")
    trPr.append(header)


def _column_widths(headers: list[str], rows: list[list[str]], total_in: float) -> list[float]:
    """Weight column widths by how much content they actually carry, instead
    of splitting evenly (or always favoring column 0) -- a report's own
    tables vary wildly in shape: a "#" column of single digits next to a
    "Development" column of full sentences needs very different widths, and
    an even split (or a fixed "column 0 is the label" assumption) wraps the
    long column to many lines while the short one sits mostly empty.

    Each column's weight is the 75th-percentile string length across its
    header + cell values (not the max, so one unusually long cell doesn't
    dominate); a floor keeps a short column from collapsing to nothing.
    """
    n_cols = len(headers)
    if n_cols <= 1:
        return [total_in]

    def typical_length(c: int) -> float:
        values = [headers[c]] + [row[c] for row in rows if c < len(row)]
        lengths = sorted(len(v) for v in values) or [1]
        idx = min(len(lengths) - 1, int(len(lengths) * 0.75))
        return max(lengths[idx], len(headers[c]), 1)

    weights = [max(typical_length(c), 4) for c in range(n_cols)]
    widths = [total_in * w / sum(weights) for w in weights]
    floor = 0.5
    deficit = sum(max(0.0, floor - w) for w in widths)
    if deficit:
        widths = [max(floor, w) for w in widths]
        surplus_total = sum(w - floor for w in widths if w > floor)
        if surplus_total > 0:
            widths = [
                w - deficit * ((w - floor) / surplus_total) if w > floor else w for w in widths
            ]
    scale = total_in / sum(widths)
    return [w * scale for w in widths]


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


class ExportBuilder:
    """Streaming-ish docx builder: call add_cover_page / add_toc once, then
    add_report once per report, then to_bytes(). Each add_report call parses
    its own markdown internally and lets that structure go out of scope when
    it returns, so only one report's parsed form is ever live alongside the
    growing Document -- see the module docstring."""

    def __init__(self) -> None:
        self.doc = Document(str(TEMPLATE_PATH))
        # The template opens with one blank paragraph; drop it so the cover
        # page starts clean.
        first = self.doc.paragraphs[0] if self.doc.paragraphs else None
        if first is not None and not first.text and not first.runs:
            first._p.getparent().remove(first._p)
        self._pending_page_break = False
        self._in_landscape = False

    # -- cover / TOC --------------------------------------------------

    def add_cover_page(self, *, scope_summary: str, run_date: str) -> None:
        section = self.doc.sections[0]
        section.different_first_page_header_footer = True
        self._configure_footer(section, run_date)

        self.doc.add_paragraph("AutoStrat Loom", style="Loom Cover Subtitle")
        self.doc.add_paragraph("Market Insights", style="Loom Cover Title")
        if scope_summary:
            self.doc.add_paragraph(scope_summary, style="Loom Cover Subtitle")
        self.doc.add_paragraph(f"Generated {run_date}", style="Loom Cover Subtitle")
        self._page_break()

    def add_toc(self) -> None:
        # Deliberately not doc.add_heading(): a real "Heading 1" paragraph
        # has an outline level, and the TOC field below (\o "1-2") collects
        # every paragraph in that outline-level range -- including its own
        # title, if that title used a heading style. This mimics Heading 1
        # visually without giving it an outline level.
        title = self.doc.add_paragraph()
        run = title.add_run("Table of Contents")
        run.bold = True
        run.font.size = Pt(15)
        run.font.color.rgb = _ACCENT
        title.paragraph_format.space_before = Pt(10)
        title.paragraph_format.space_after = Pt(6)

        p = self.doc.add_paragraph()
        _insert_toc_field(p)
        self._page_break()

    def _configure_footer(self, section, run_date: str) -> None:
        # different_first_page_header_footer=True means section.first_page_footer
        # covers the cover page (left blank) and section.footer covers every
        # page after it within this section.
        footer = section.footer
        p = footer.paragraphs[0]
        p.text = ""
        p.style = self.doc.styles["Loom Footer"]
        p.add_run("AutoStrat Loom Market Insights  ·  ")
        run = p.add_run()
        r = run._r
        begin = OxmlElement("w:fldChar")
        begin.set(qn("w:fldCharType"), "begin")
        instr = OxmlElement("w:instrText")
        instr.set(qn("xml:space"), "preserve")
        instr.text = "PAGE"
        end = OxmlElement("w:fldChar")
        end.set(qn("w:fldCharType"), "end")
        for el in (begin, instr, end):
            r.append(el)
        p.add_run(f"  ·  {run_date}")

        section.first_page_footer.paragraphs[0].text = ""

    # -- per-report entry point ----------------------------------------

    def add_report(self, markdown_text: str, *, report_number: int, title: str) -> None:
        if self._pending_page_break:
            self._page_break()
        self._pending_page_break = True

        self.doc.add_heading(title, level=1)

        try:
            parsed = parse_report(markdown_text, report_number=report_number)
            if isinstance(parsed.opening, SCQABlock):
                self._render_scqa(parsed.opening)
            elif isinstance(parsed.opening, KeyInsightsBox):
                self._render_key_insights(parsed.opening)
            self._render_blocks(parsed.blocks)
            for w in parsed.warnings:
                logger.warning(w)
        except Exception:  # noqa: BLE001 - one bad report must not fail the pack
            logger.exception("Report %s (%s): render failed, falling back to raw text", report_number, title)
            self._render_raw_fallback(markdown_text)

    def _render_raw_fallback(self, markdown_text: str) -> None:
        for line in markdown_text.splitlines() or [markdown_text]:
            self.doc.add_paragraph(line)

    # -- block dispatch --------------------------------------------------

    def _render_blocks(self, blocks: list) -> None:
        i = 0
        n = len(blocks)
        while i < n:
            grid_idx = self._harvey_grid_run_end(blocks, i)
            if grid_idx is not None:
                # Its exhibit-caption heading and/or "Legend:" paragraph (if
                # either immediately precedes it) enter landscape together
                # with the grid, so nothing orphans on the portrait page
                # before it -- a section break defeats keep-with-next, so
                # this is the only way the caption stays with its table.
                self._enter_landscape()
                for j in range(i, grid_idx):
                    self._render_block(blocks[j])
                self._render_harvey_grid(blocks[grid_idx])
                i = grid_idx + 1
                while i < n and isinstance(blocks[i], Paragraph) and blocks[i].style == "footnote":
                    self._render_paragraph(blocks[i])
                    i += 1
                self._exit_landscape()
                continue

            self._render_block(blocks[i])
            i += 1

    @staticmethod
    def _harvey_grid_run_end(blocks: list, i: int) -> int | None:
        """If blocks[i] starts a short run of (exhibit Heading, "Legend:"
        Paragraph) immediately followed by a HarveyBallGrid, return the
        grid's index. None if blocks[i] doesn't start such a run."""
        j = i
        n = len(blocks)
        if j < n and isinstance(blocks[j], Heading):
            j += 1
        if j < n and isinstance(blocks[j], Paragraph) and blocks[j].style == "legend":
            j += 1
        if j < n and isinstance(blocks[j], exhibits.HarveyBallGrid):
            return j
        return None

    def _render_block(self, block) -> None:
        if isinstance(block, Heading):
            self.doc.add_heading(block.text, level=min(max(block.level, 1), 3))
        elif isinstance(block, HorizontalRule):
            _hr_paragraph(self.doc)
        elif isinstance(block, Paragraph):
            self._render_paragraph(block)
        elif isinstance(block, TableBlock):
            self._render_table(block)
        elif isinstance(block, BulletListBlock):
            self._render_bullet_list(block)
        elif isinstance(block, ExhibitBlock):
            self._render_exhibit(block.content)
        elif isinstance(block, exhibits.HarveyBallGrid):
            # Reached only if a grid appears with no preceding legend --
            # still gets its own landscape section.
            self._enter_landscape()
            self._render_harvey_grid(block)
            self._exit_landscape()
        else:
            logger.warning("Unhandled block type %s, skipped", type(block).__name__)

    # -- paragraphs / runs ------------------------------------------------

    def _add_text_run(self, paragraph, run: Run) -> None:
        if run.link:
            _add_hyperlink(paragraph, run.link, run.text, bold=run.bold, italic=run.italic)
            return
        r = paragraph.add_run(run.text)
        if run.bold:
            r.bold = True
        if run.italic:
            r.italic = True
        if run.tag == "confidence":
            r.font.highlight_color = WD_COLOR_INDEX.GRAY_25
        elif run.tag == "staleness":
            r.font.highlight_color = WD_COLOR_INDEX.YELLOW

    def _render_paragraph(self, block: Paragraph) -> None:
        if not block.runs or not block.text.strip():
            return
        style_name = {
            "so_what": "Loom So What",
            "footnote": "Loom Footnote",
        }.get(block.style)
        p = self.doc.add_paragraph(style=style_name)
        if block.keep_with_next:
            p.paragraph_format.keep_with_next = True
        for run in block.runs:
            self._add_text_run(p, run)

    def _render_bullet_list(self, block: BulletListBlock) -> None:
        for runs in block.items:
            p = self.doc.add_paragraph(style="List Bullet")
            for run in runs:
                self._add_text_run(p, run)

    # -- Key Insights / Governing Insight callouts ------------------------

    def _render_key_insights(self, box: KeyInsightsBox) -> None:
        if not box.items:
            return
        table = self.doc.add_table(rows=0, cols=1)
        _set_table_width(table, _USABLE_WIDTH_PORTRAIT_IN)
        for item in box.items:
            cell = table.add_row().cells[0]
            cell.width = Inches(_USABLE_WIDTH_PORTRAIT_IN)
            _shade_cell(cell, _KEY_INSIGHT_SHADE)
            p = cell.paragraphs[0]
            p.style = self.doc.styles["List Bullet"]
            if item.lead:
                r = p.add_run(item.lead)
                r.bold = True
                p.add_run("  ")
            p.add_run(item.rest)
            # Skip the badge when the lead already spells out confidence
            # inline (e.g. "FACT — High confidence") -- appending one would
            # just repeat the same word twice in one bullet.
            if item.confidence and "confidence" not in item.lead.lower():
                badge = p.add_run(f"  (Confidence: {item.confidence})")
                badge.bold = True
                badge.font.size = Pt(8.5)
        self.doc.add_paragraph()

    def _render_scqa(self, scqa: SCQABlock) -> None:
        rows = [
            ("Situation", scqa.situation, _SCQA_SHADE),
            ("Complication", scqa.complication, _SCQA_SHADE),
            ("Question", scqa.question, _SCQA_SHADE),
            ("Answer", scqa.answer, _SCQA_ANSWER_SHADE),
        ]
        rows = [r for r in rows if r[1]]
        if not rows:
            return
        table = self.doc.add_table(rows=0, cols=1)
        _set_table_width(table, _USABLE_WIDTH_PORTRAIT_IN)
        for label, text, shade in rows:
            cell = table.add_row().cells[0]
            cell.width = Inches(_USABLE_WIDTH_PORTRAIT_IN)
            _shade_cell(cell, shade)
            p = cell.paragraphs[0]
            r = p.add_run(f"{label}.  ")
            r.bold = True
            p.add_run(text)
        self.doc.add_paragraph()

    # -- plain markdown tables ---------------------------------------------

    def _render_table(self, block: TableBlock) -> None:
        n_cols = len(block.headers)
        if n_cols == 0:
            return
        total_width = _USABLE_WIDTH_LANDSCAPE_IN if self._in_landscape else _USABLE_WIDTH_PORTRAIT_IN
        widths = _column_widths(block.headers, block.rows, total_width)
        table = self.doc.add_table(rows=1, cols=n_cols)
        table.style = "Loom Table"
        _set_table_width(table, sum(widths), widths)
        _set_repeat_header_row(table)

        hdr_cells = table.rows[0].cells
        for c, h in enumerate(block.headers):
            p = hdr_cells[c].paragraphs[0]
            run = p.add_run(h)
            run.bold = True
            _shade_cell(hdr_cells[c], _HEADER_SHADE)

        for row in block.rows:
            cells = table.add_row().cells
            for c in range(n_cols):
                val = row[c] if c < len(row) else ""
                cells[c].width = Inches(widths[c])
                cells[c].paragraphs[0].add_run(val)
        self.doc.add_paragraph()

    # -- exhibits ------------------------------------------------------

    def _render_exhibit(self, content) -> None:
        if isinstance(content, exhibits.TamSamSom):
            self._render_tam_sam_som(content)
        elif isinstance(content, exhibits.FallbackExhibit):
            self._render_fallback_exhibit(content)
        else:
            logger.warning("Unhandled exhibit type %s", type(content).__name__)

    def _render_tam_sam_som(self, block: "exhibits.TamSamSom") -> None:
        if not block.rings:
            return
        self._add_ring(self.doc, block.rings, 0, _USABLE_WIDTH_PORTRAIT_IN)
        self.doc.add_paragraph()

    def _add_ring(self, container, rings: list["exhibits.Ring"], idx: int, width_in: float) -> None:
        if idx >= len(rings):
            return
        ring = rings[idx]
        table = container.add_table(rows=1, cols=1)
        _set_table_width(table, width_in)
        cell = table.cell(0, 0)
        cell.width = Inches(width_in)
        _shade_cell(cell, _RING_SHADES[idx % len(_RING_SHADES)])

        p = cell.paragraphs[0]
        label_run = p.add_run(ring.label)
        label_run.bold = True
        if ring.value:
            p.add_run("  " + ring.value)
        if ring.status:
            badge = p.add_run(f"  [{ring.status}]")
            badge.bold = True
            badge.font.size = Pt(8.5)
        if ring.definition:
            p2 = cell.add_paragraph(ring.definition)
            p2.style = self.doc.styles["Loom Caption"]

        if idx + 1 < len(rings):
            inner_width = max(width_in - 0.5, 1.2)
            self._add_ring(cell, rings, idx + 1, inner_width)
            # Bottom padding after the nested inner table -- without this
            # every ring's own shading ends exactly where the inner table
            # ends, so all three levels terminate flush and the whole
            # exhibit reads as stacked bands instead of nested containment.
            spacer = cell.add_paragraph()
            spacer.paragraph_format.space_before = Pt(0)
            spacer.paragraph_format.space_after = Pt(8)

    def _render_fallback_exhibit(self, block: "exhibits.FallbackExhibit") -> None:
        lines = block.raw_text.splitlines() or [block.raw_text]
        table = self.doc.add_table(rows=1, cols=1)
        _set_table_width(table, _USABLE_WIDTH_PORTRAIT_IN)
        cell = table.cell(0, 0)
        cell.width = Inches(_USABLE_WIDTH_PORTRAIT_IN)
        _shade_cell(cell, _FALLBACK_SHADE)
        _set_cell_borders(cell, _FALLBACK_BORDER)

        first = cell.paragraphs[0]
        first.style = self.doc.styles["Loom Monospace"]
        for i, line in enumerate(lines):
            p = first if i == 0 else cell.add_paragraph(style=self.doc.styles["Loom Monospace"])
            run = p.add_run(line if line else " ")
            _set_run_font(run, _SYMBOL_FONT)
        self.doc.add_paragraph()

    def _render_harvey_grid(self, grid: "exhibits.HarveyBallGrid") -> None:
        n_cols = len(grid.headers)
        if n_cols == 0:
            return
        label_w = min(2.6, _USABLE_WIDTH_LANDSCAPE_IN * 0.35)
        symbol_w = (_USABLE_WIDTH_LANDSCAPE_IN - label_w) / max(1, n_cols - 1)
        widths = [label_w] + [symbol_w] * (n_cols - 1)

        table = self.doc.add_table(rows=1, cols=n_cols)
        table.style = "Loom Table"
        _set_table_width(table, sum(widths), widths)
        _set_repeat_header_row(table)

        hdr_cells = table.rows[0].cells
        for c, h in enumerate(grid.headers):
            p = hdr_cells[c].paragraphs[0]
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT if c == 0 else WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run(h)
            run.bold = True
            _shade_cell(hdr_cells[c], _HEADER_SHADE)

        for row in grid.rows:
            cells = table.add_row().cells
            for c in range(n_cols):
                val = row[c] if c < len(row) else ""
                cells[c].width = Inches(widths[c])
                p = cells[c].paragraphs[0]
                if c == 0:
                    p.add_run(val)
                else:
                    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    run = p.add_run(val)
                    _set_run_font(run, _SYMBOL_FONT)
        self.doc.add_paragraph()

    # -- landscape section handling ---------------------------------------

    def _enter_landscape(self) -> None:
        if self._in_landscape:
            return
        base = self.doc.sections[0]
        new_section = self.doc.add_section(WD_SECTION.NEW_PAGE)
        new_section.orientation = WD_ORIENT.LANDSCAPE
        # python-docx doesn't swap dimensions for you when orientation changes.
        new_section.page_width = base.page_height
        new_section.page_height = base.page_width
        self._in_landscape = True
        self._pending_page_break = False

    def _exit_landscape(self) -> None:
        if not self._in_landscape:
            return
        base = self.doc.sections[0]
        new_section = self.doc.add_section(WD_SECTION.NEW_PAGE)
        new_section.orientation = WD_ORIENT.PORTRAIT
        new_section.page_width = base.page_width
        new_section.page_height = base.page_height
        self._in_landscape = False
        self._pending_page_break = False

    # -- misc ---------------------------------------------------------

    def _page_break(self) -> None:
        p = self.doc.add_paragraph()
        p.add_run().add_break(WD_BREAK.PAGE)

    def to_bytes(self) -> bytes:
        import io

        buf = io.BytesIO()
        self.doc.save(buf)
        return buf.getvalue()
